# app.yaml
name: databricks-stewardship-app
runtime: python
command:
  - "uvicorn"
  - "main:app"
  - "--reload"

env:
  - name: DATABRICKS_SCHEMA
    value: default

  - name: DATABRICKS_HOST
    value: https://adb-1234567890123456.7.azuredatabricks.net

  - name: DATABRICKS_HTTP_PATH
    value: sql/protocolv1/o/1234567890123456/0123-123456-abcdefg

  - name: DATABRICKS_CATALOG
    value: hive_metastore
