# app.yaml
name: databricks-stewardship-app
runtime: python
command:
  - "uvicorn"
  - "main:app"
  - "--reload"

env:
  - name: DATABRICKS_SCHEMA
    value: wanderbricks

  - name: DATABRICKS_HOST
    value: dbc-590f1264-5ff1.cloud.databricks.com

  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/88aed6e37190d6d8
